package com.yet.bitmessage.feature.chats.conversations.settings.store

import com.app.domain.repository.IdentityRepository
import com.app.domain.repository.SettingsRepository
import com.app.domain.usecase.PanicWipeUseCase
import com.arkivanov.mvikotlin.core.store.Reducer
import com.arkivanov.mvikotlin.core.store.SimpleBootstrapper
import com.arkivanov.mvikotlin.core.store.Store
import com.arkivanov.mvikotlin.core.store.StoreFactory
import com.arkivanov.mvikotlin.extensions.coroutines.CoroutineExecutor
import kotlinx.coroutines.launch

internal class SettingsStoreFactory(
    private val storeFactory: StoreFactory,
    private val settingsRepository: SettingsRepository,
    private val identityRepository: IdentityRepository,
    private val panicWipe: PanicWipeUseCase,
) {
    fun create(): SettingsStore =
        object : SettingsStore,
            Store<SettingsStore.Intent, SettingsStore.State, SettingsStore.Label> by storeFactory.create(
                name = "SettingsStore",
                initialState = SettingsStore.State(),
                bootstrapper = SimpleBootstrapper(SettingsStore.Action.Load),
                executorFactory = ::ExecutorImpl,
                reducer = ReducerImpl,
            ) {}

    private object ReducerImpl : Reducer<SettingsStore.State, SettingsStore.Msg> {
        override fun SettingsStore.State.reduce(msg: SettingsStore.Msg): SettingsStore.State =
            when (msg) {
                is SettingsStore.Msg.NicknameLoaded -> copy(nickname = msg.nickname)
                is SettingsStore.Msg.IdentityLoaded -> copy(npub = msg.npub, fingerprint = msg.fingerprint)
                is SettingsStore.Msg.Wiping -> copy(isWiping = msg.wiping)
            }
    }

    private inner class ExecutorImpl :
        CoroutineExecutor<SettingsStore.Intent, SettingsStore.Action, SettingsStore.State, SettingsStore.Msg, SettingsStore.Label>() {

        override fun executeAction(action: SettingsStore.Action) {
            when (action) {
                SettingsStore.Action.Load -> {
                    scope.launch {
                        settingsRepository.observeNickname().collect { dispatch(SettingsStore.Msg.NicknameLoaded(it)) }
                    }
                    scope.launch { loadIdentity() }
                }
            }
        }

        override fun executeIntent(intent: SettingsStore.Intent) {
            when (intent) {
                is SettingsStore.Intent.NicknameChanged -> scope.launch {
                    settingsRepository.setNickname(intent.text)
                }
                SettingsStore.Intent.PanicWipe -> scope.launch {
                    dispatch(SettingsStore.Msg.Wiping(true))
                    panicWipe()
                    // Identity is regenerated by the wipe — reflect the new one.
                    loadIdentity()
                    dispatch(SettingsStore.Msg.Wiping(false))
                }
            }
        }

        private suspend fun loadIdentity() {
            val identity = identityRepository.myIdentity()
            dispatch(SettingsStore.Msg.IdentityLoaded(identity.nostrNpub, identity.fingerprint.value))
        }
    }
}
