package com.app.domain.repository

import com.app.domain.model.Fingerprint
import com.app.domain.model.MyIdentity
import kotlinx.coroutines.flow.Flow

/**
 * Our own identity and peer-verification state. The QR / Noise challenge-response mechanics are
 * infrastructure (crypto layer); the domain only deals with verified fingerprints.
 */
interface IdentityRepository {

    suspend fun myIdentity(): MyIdentity

    fun observeVerifiedFingerprints(): Flow<Set<Fingerprint>>

    suspend fun isVerified(fingerprint: Fingerprint): Boolean

    suspend fun setVerified(fingerprint: Fingerprint, verified: Boolean)

    /** Wipe the cryptographic identity (regenerated by the implementation). */
    suspend fun panicWipe()
}
