package com.yet.bitmessage.ui.component.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val QrCodeScanner: ImageVector
    get() {
        if (_QrCodeScanner != null) {
            return _QrCodeScanner!!
        }
        _QrCodeScanner = ImageVector.Builder(
            name = "QrCodeScanner",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                moveTo(80f, 280f)
                verticalLineToRelative(-200f)
                horizontalLineToRelative(200f)
                verticalLineToRelative(80f)
                lineTo(160f, 160f)
                verticalLineToRelative(120f)
                lineTo(80f, 280f)
                close()
                moveTo(80f, 880f)
                verticalLineToRelative(-200f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(80f)
                lineTo(80f, 880f)
                close()
                moveTo(680f, 880f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(-120f)
                horizontalLineToRelative(80f)
                verticalLineToRelative(200f)
                lineTo(680f, 880f)
                close()
                moveTo(800f, 280f)
                verticalLineToRelative(-120f)
                lineTo(680f, 160f)
                verticalLineToRelative(-80f)
                horizontalLineToRelative(200f)
                verticalLineToRelative(200f)
                horizontalLineToRelative(-80f)
                close()
                moveTo(700f, 700f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(700f, 580f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(640f, 640f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(580f, 700f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(520f, 640f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(640f, 520f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(580f, 580f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(520f, 520f)
                horizontalLineToRelative(60f)
                verticalLineToRelative(60f)
                horizontalLineToRelative(-60f)
                verticalLineToRelative(-60f)
                close()
                moveTo(760f, 200f)
                verticalLineToRelative(240f)
                lineTo(520f, 440f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(240f)
                close()
                moveTo(440f, 520f)
                verticalLineToRelative(240f)
                lineTo(200f, 760f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(240f)
                close()
                moveTo(440f, 200f)
                verticalLineToRelative(240f)
                lineTo(200f, 440f)
                verticalLineToRelative(-240f)
                horizontalLineToRelative(240f)
                close()
                moveTo(380f, 700f)
                verticalLineToRelative(-120f)
                lineTo(260f, 580f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(120f)
                close()
                moveTo(380f, 380f)
                verticalLineToRelative(-120f)
                lineTo(260f, 260f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(120f)
                close()
                moveTo(700f, 380f)
                verticalLineToRelative(-120f)
                lineTo(580f, 260f)
                verticalLineToRelative(120f)
                horizontalLineToRelative(120f)
                close()
            }
        }.build()

        return _QrCodeScanner!!
    }

@Suppress("ObjectPropertyName")
private var _QrCodeScanner: ImageVector? = null
